config/routes.rb
Rails.application.routes.draw do
  root to:'activities#index'
  resources :activities
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
     @activity.duration = params[:hh].to_i*60*60+params[:mm].to_i*60
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    @activity.duration = params[:hh].to_i*60*60+params[:mm].to_i*60
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :date, :duration)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:home,]
  protect_from_forgery with: :null_session


  private
  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def seconds_to_hms(sec)
    "%02d:%02d:%02d" % [sec / 3600, sec / 60 % 60, sec % 60]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="  align-self-center " style="width: 40%;">
      <div class="card card-signin flex-row my-5">
        <div class=" d-none d-md-flex">
          <!-- Background image for card set in CSS! -->
        </div>
        <div class="card-body">
            <h3 class=" text-center">New Activity</h3>
            <%= form_with(model: activity, local: true) do |form| %>
              <% if activity.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

                  <ul>
                    <% activity.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="form-group">
                <%= form.label :name %>
                <select class="form-control" name="activity[name]" id="exampleFormControlSelect1" required>
                  <option value="">Select activity</option>
                  <option>Walking</option>
                  <option>Hiking</option>
                  <option>Cycling</option>
                  <option>Rowing</option>
                  <option>Running</option>
                  <option>Swimming</option>
                  <option>Strength Training</option>
                  <option>Situps</option>
                  <option>Pushups</option>
                  <option>Mountain Biking</option>
                </select>
              </div>

              <div class="form-group">
                <%= form.label :date %>
                <%= form.date_select :date,required: true,class:"form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :duration %><br>
               <span>Hours</span> <input type="number" name="hh" class="mr-5 " maxlength="60" required>                <span>Min</span> <input type="number" name="mm" maxlength="60" required>

              </div>

              <div class="actions">
                <%= form.submit class:"btn btn-primary" %>

                <%= link_to 'Back', activities_path ,class: "pull-right mt-5"%>
              </div>
            <% end %>
            </form>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<section class="content">
<div class="container">
  <div class="row justify-content-md-center">
    <div class="  align-self-center " style="width: 40%;">
      <div class="card card-signin flex-row my-5">
        <div class=" d-none d-md-flex">
          <!-- Background image for card set in CSS! -->
        </div>
        <div class="card-body">
          <h3 class=" text-center">Edit Activity</h3>
          <%= form_with(model: @activity, local: true) do |form| %>
            <% if @activity.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

                <ul>
                  <% @activity.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <%= form.label :name %>
              <%= form.select "name", options_for_select([ "Walking", "Hiking","Cycling","Rowing","Running","Swimming","Strength Training","Situps","Pushups","Mountain Biking" ],@activity.name),{},required: true,class: "form-control" %>

            </div>

            <div class="form-group">
              <%= form.label :date %>
              <%= form.date_select :date,value:@activity.date, required: true,class:"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :duration %><br>
              <span>Hours</span> <input type="number" value=<%= seconds_to_hms(@activity.duration).split(':')[0] %> name="hh" class="mr-5 " maxlength="60" required>
              <span>Min</span> <input type="number" value=<%= seconds_to_hms(@activity.duration).split(':')[1] %> name="mm" maxlength="60" required>

            </div>

            <div class="actions">
              <%= form.submit class:"btn btn-primary" %>

              <%= link_to 'Back', activities_path ,class: "pull-right mt-5"%>
            </div>
          <% end %>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/activities/index.html.erb
<style>
  .click{
    cursor: pointer;
  }
  .card:hover{
    box-shadow: 0 1rem 1.5rem 0 rgba(0, 0, 0, 0.1);
  }
    .col-sm{
      min-width: 20%;
      max-width: 20%;
      margin-top: 30px;
    }
</style>
<section class="content" >
<div class="container" style="">

  <% if flash[:notice] %>
    <input type="hidden" id="flash_notice" value="<%= flash[:notice] %>" class="messages notice">
    <%= javascript_tag " alert($('#flash_notice').val()) " %>
  <% end %>

<h2>My Activities <%= link_to 'New Activity', new_activity_path,class: "pull-right btn btn-primary" %>
</h2>

  <div class="row">
  <% @activities.each do |activity| %>

  <div id = "e" class="col-sm click" value="3">
    <%= link_to  activity do %>

  <div class="card card-stats">
        <div class="card-body text-center" style="height: 150px;">
          <div class="text-center">
              <div class="">
                <img src="<%= asset_path activity.name %>">
              </div>
          </div>
          <h4><%= activity.name %></h4>
        </div>
      </div>
    </div>
      <%end %>
    <%end %>

  </div>
<br>
</div>
</section>
<section id="intro" class="section intro">
  <div class="container">
    <div class="col-md-8 col-md-offset-2 text-center">
      <h3>Boost your Healt and Life</h3>
      <p>For some people, putting in the hard work that it takes to stay fit is as natural as sleeping, eating, and breathing—it's a necessary part of their life.So when you don't feel like you can finish another rep, or when you just don't want to get up for that 5 a.m. wakeup call, just remember these words of wisdom from some of the fittest men who have ever walked the earth</p>
    </div>
  </div>
</section>

<script>
</script>

app/views/activities/new.html.erb
<section class="content">


<%= render 'form', activity: @activity %>

</section>

app/views/activities/show.html.erb
<section class="content">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="  align-self-center " style="width: 40%;">
        <div class="card card-signin flex-row my-5">
          <div class=" d-none d-md-flex">
            <!-- Background image for card set in CSS! -->
          </div>
          <div class="card-body text-center">
            <h3 class=" text-center">Show Activity</h3>

            <img src="<%= asset_path @activity.name %>">
            <p id="notice"><%= notice %></p>
<div>
            <p>
              <strong>Name:</strong>
              <%= @activity.name %>
            </p>

            <p>
              <strong>Date:</strong>
              <%= @activity.date %>
            </p>

            <p>
              <strong>Duration:</strong>
              <%= seconds_to_hms(@activity.duration) %>
            </p>
</div>
            <%= link_to 'Edit', edit_activity_path(@activity),class: "btn btn-primary" %> |
            <%= link_to 'Destroy', activity_path, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-primary"%>|
            <%= link_to 'Back', activities_path,class: "btn btn-primary" %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<section class="banner" role="banner" style="background-image: url(<%= asset_path('banner.jpg') %>);">
  <!-- banner text -->
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="banner-text text-center">
        <h1>Beauty SPA</h1>
        <p>Lorem ipsum dolor sit ametcursus magna vel ipsum dolor sit amet scelerisque<br/>
          Lorem consectetur adipiscing elit.<br/> </p></div>
      <!-- banner text -->
    </div>
  </div>
</section>


<section id="intro" class="section intro">
  <div class="container">
    <div class="col-md-8 col-md-offset-2 text-center">
      <h3>Boost your Healt and Life</h3>
      <p>For some people, putting in the hard work that it takes to stay fit is as natural as sleeping, eating, and breathing—it's a necessary part of their life.So when you don't feel like you can finish another rep, or when you just don't want to get up for that 5 a.m. wakeup call, just remember these words of wisdom from some of the fittest men who have ever walked the earth</p>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div id="map-row" class="row">
      <div class="col-xs-12">
        <div id="map-overlay" class="row" style="">
          <div class="col-xs-6">
            <h2 style="margin-top:0;color:#fff;">Contact us</h2>
            <address style="color:#fff;">
              <strong>Company name</strong><br>
              1234 Street Dr.<br>
              Vancouver, BC<br>
              Canada<br>
              V6G 1G9<br>
              <abbr title="Phone">Tel:</abbr> (604) 555-4321
            </address>
            © 2020 Company Name. All Rights Reserved <br/>
          </div>
          <div class="col-xs-6">
            <h4 style="margin-top:0;color:#fff;">Menu</h4>
            <address style="">

              <ul class="">
                <li><a href="#gallery">My Activities</a></li>
                <li><a href="#intro">About</a></li>
              </ul>
            </address>
          </div>

        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header" style="top: 0px; ">
  <div class="header-content clearfix"> <span class="logo"><a href="/" class="mb-5">FITNESS</a></span>
    <nav class="navigation" role="navigation">
      <ul class="primary-nav">
        <li><a href="/activities">My Activicies</a></li>
        <li><a href="#intro">About</a></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
              <span>
                Sign Out
                <i class="fa fa-sign-out"></i>
              </span>
          <% end %>
        </li>

      </ul>
    </nav>
    <a href="#" class="nav-toggle">Menu<span></span></a> </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('fav.png'),sizes: "228x228" %>
  </head>

  <body>
  <% unless controller.class.to_s.split('::')[0] == 'Devise' %>
  <%= render "layouts/header" %>
    <%end %>
    <%= yield %>
    <% unless controller.class.to_s.split('::')[0] == 'Devise' %>
      <%= render 'layouts/footer' %>
   <%end %>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
</html>